name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.6
  - conda-build
  - anaconda-client
  - numpy
  - pandas
  - matplotlib
  - scipy
  - xarray
  - six
  - pytz
  - pip
  - pip:
    - tqdm
    - pytest
    - pytest-cov
    - motionless
    - python-dateutil
    - certifi
